# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

# tg频道抓取
- type: tgchannel
  options:
    channel: bhsghost
    num: 200
- type: tgchannel
  options:
    channel: sharecentre
    num: 200
- type: tgchannel
  options:
    channel: fproxies
    num: 200

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml
