# 订阅链接
- type: subscribe
  options:
    url: 

# tg频道抓取
- type: tgchannel
  options:
    channel: bhsghost
    num: 200
- type: tgchannel
  options:
    channel: sharecentre
    num: 200
- type: tgchannel
  options:
    channel: fproxies
    num: 200

# clash格式订阅链接
- type: clash
  options:
    url: 
    
 # 网页模糊抓取
- type: webfuzz
  options:
    url: https://free-ss.site
- type: webfuzz
  options:
    url: https://bihai.cf
