# 模糊抓取订阅链接
#- type: webfuzzsub
#  options:
#    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
#- type: subscribe
#  options:
#    url: https://raw.githubusercontent.com/satrom/V2SSR/master/1.txt
    
# 网页模糊抓取
#- type: webfuzz
#  options:
#    url: https://free-ss.site
    
# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: bhsghost
    num: 200
- type: tgchannel
  options:
    channel: fproxies
    num: 200
- type: tgchannel
  options:
    channel: sharecentre
    num: 200
    
# 翻墙党论坛抓取
#- type: web-fanqiangdang
#  options:
#    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
#- type: clash
#  options:
#    url: https://ss.dswang.ga:8443

# 某个网站抓取
#- type: web-freessrxyz
#  options:
#    url: 
