# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: 

# 网页模糊抓取
- type: webfuzz
  options:
    url: 

# 翻墙党
- type: web-fanqiangdang
  options:
    url: 
    num: 200

# 某个网站抓取
- type: web-freessrxyz
  options:
    url: 
 
# tg频道抓取
- type: tgchannel
  options:
    channel: bhsghost
    num: 200
- type: tgchannel
  options:
    channel: sharecentre
    num: 200
- type: tgchannel
  options:
    channel: fproxies
    num: 200

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/satrom/V2SSR/master/V2RAY/Sub.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/satrom/V2SSR/master/SSR/Sub.txt
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/satrom/V2SSR/master/SSR/Day.txt 
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/satrom/V2SSR/master/SS/Sub.txt 
- type: subscribe
  options:
    url: https://www.vtworay.com/modules/servers/V2raySocks/osubscribe.php?sid=5063&token=cG4CsQNoHcQs

# clash格式订阅链接
- type: clash
  options:
    url: https://suo.yt/qarTaop
