# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://free-ss.site
    
# tg频道抓取
- type: tgchannel
  options:
    channel: ssrlists
    num: 200
- type: tgchannel
  options:
    channel: ssrsub
    num: 200    
- type: tgchannel
  options:
    channel: bhsghost
    num: 200
- type: tgchannel
  options:
    channel: sharecentre
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://ss.dswang.ga:8443
- type: clash
  options:
    url: https://sub.cm/lwcgawT
    
# 某个网站抓取
#- type: web-freessrxyz
#  options:
#    url: 
